#!/usr/bin/env bash
# FLUER Protocol — Mainnet Deployment Script
# Run: ./scripts/deploy-mainnet.sh
# Prerequisites: Solana CLI configured, Anchor installed, admin keypair ready

set -euo pipefail

# ── Colors ────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
RESET='\033[0m'

log() { echo -e "${CYAN}[FLUER]${RESET} $1"; }
success() { echo -e "${GREEN}[✓]${RESET} $1"; }
warn() { echo -e "${YELLOW}[!]${RESET} $1"; }
err() { echo -e "${RED}[✗]${RESET} $1" >&2; exit 1; }

echo ""
echo -e "${BOLD}FLUER Protocol — Mainnet Deployment${RESET}"
echo "══════════════════════════════════════"
echo ""

# ── Pre-flight checks ─────────────────────────────────────────
log "Running pre-flight checks..."

command -v solana >/dev/null 2>&1 || err "solana CLI not found"
command -v anchor >/dev/null 2>&1 || err "anchor CLI not found"
command -v cargo >/dev/null 2>&1 || err "cargo not found"

SOLANA_CLUSTER=$(solana config get | grep "RPC URL" | awk '{print $3}')
log "Current cluster: $SOLANA_CLUSTER"

if [[ "$SOLANA_CLUSTER" != *"mainnet"* ]]; then
    warn "Not on mainnet! Set cluster with: solana config set --url mainnet-beta"
    read -p "Continue anyway? (y/N): " confirm
    [[ "$confirm" != "y" ]] && exit 1
fi

WALLET=$(solana address)
log "Deployer wallet: $WALLET"

BALANCE=$(solana balance | awk '{print $1}')
log "Balance: $BALANCE SOL"

if (( $(echo "$BALANCE < 10" | bc -l) )); then
    err "Insufficient SOL balance. Need at least 10 SOL for deployment."
fi

success "Pre-flight checks passed"
echo ""

# ── Build programs ────────────────────────────────────────────
log "Building Anchor programs (release)..."
cd programs
anchor build
success "Programs built"

# ── Verify program sizes ──────────────────────────────────────
log "Verifying program binary sizes..."
for prog in fluer_launchpad fluer_perp_engine fluer_prediction fluer_token; do
    SIZE=$(wc -c < target/deploy/${prog}.so)
    SIZE_KB=$((SIZE / 1024))
    log "  $prog: ${SIZE_KB}KB / 1024KB limit"
    if [ $SIZE_KB -gt 900 ]; then
        warn "  $prog is close to the size limit!"
    fi
done
success "Size check passed"
echo ""

# ── Deploy programs ───────────────────────────────────────────
log "Deploying programs to mainnet..."
echo ""

PROGRAMS=(
    "fluer_launchpad"
    "fluer_perp_engine"
    "fluer_prediction"
    "fluer_token"
)

declare -A PROGRAM_IDS

for prog in "${PROGRAMS[@]}"; do
    log "Deploying $prog..."
    
    OUTPUT=$(anchor deploy --program-name $prog --provider.cluster mainnet 2>&1)
    
    PROG_ID=$(echo "$OUTPUT" | grep "Program Id:" | awk '{print $3}')
    
    if [ -z "$PROG_ID" ]; then
        # Try parsing from existing keypair
        KEYPAIR="target/deploy/${prog}-keypair.json"
        if [ -f "$KEYPAIR" ]; then
            PROG_ID=$(solana-keygen pubkey "$KEYPAIR")
        else
            err "Failed to deploy $prog"
        fi
    fi
    
    PROGRAM_IDS[$prog]=$PROG_ID
    success "$prog deployed: $PROG_ID"
done

echo ""
log "Saving program IDs..."

# Write to .env files
cat > ../services/api-gateway/.env.deploy << EOF
# Generated by deploy-mainnet.sh — $(date)
LAUNCHPAD_PROGRAM_ID=${PROGRAM_IDS[fluer_launchpad]}
PERP_ENGINE_PROGRAM_ID=${PROGRAM_IDS[fluer_perp_engine]}
PREDICTION_PROGRAM_ID=${PROGRAM_IDS[fluer_prediction]}
FLUER_TOKEN_PROGRAM_ID=${PROGRAM_IDS[fluer_token]}
EOF

cat > ../apps/web/.env.program-ids << EOF
# Generated by deploy-mainnet.sh — $(date)
NEXT_PUBLIC_LAUNCHPAD_PROGRAM_ID=${PROGRAM_IDS[fluer_launchpad]}
NEXT_PUBLIC_PERP_ENGINE_PROGRAM_ID=${PROGRAM_IDS[fluer_perp_engine]}
NEXT_PUBLIC_PREDICTION_PROGRAM_ID=${PROGRAM_IDS[fluer_prediction]}
NEXT_PUBLIC_FLUER_TOKEN_PROGRAM_ID=${PROGRAM_IDS[fluer_token]}
EOF

success "Program IDs saved to .env.deploy and .env.program-ids"
echo ""

# ── Initialize programs ───────────────────────────────────────
log "Initializing programs with admin config..."

FLUER_MINT=${FLUER_MINT:-""}
TREASURY=${TREASURY:-"$WALLET"}

if [ -z "$FLUER_MINT" ]; then
    warn "FLUER_MINT not set — skipping initialization"
    warn "Run initialization manually after setting FLUER_MINT"
else
    log "Initializing launchpad..."
    # In production: run initialization scripts here
    # anchor run init-launchpad -- --fluer-mint $FLUER_MINT --treasury $TREASURY
    warn "Automatic initialization not implemented — run manually"
fi

echo ""
echo -e "${BOLD}${GREEN}Deployment Summary${RESET}"
echo "══════════════════════════════════════"
for prog in "${PROGRAMS[@]}"; do
    echo -e "  ${CYAN}$prog${RESET}: ${PROGRAM_IDS[$prog]}"
done
echo ""
echo -e "${YELLOW}Next steps:${RESET}"
echo "  1. Update FLUER_MINT in all .env files"
echo "  2. Run program initialization: make init-mainnet"
echo "  3. Seed vanity pool: make vanity-gen && make vanity-upload"
echo "  4. Deploy services: docker compose up -d"
echo "  5. Deploy frontend: vercel deploy --prod"
echo ""
success "Mainnet deployment complete!"
